import type { Metadata } from "next";
import "./globals.css";
import SideBar from "./components/sideBar";

import {Provider} from "./globalState/Provider";
import { ToastProvider } from "./components/toast/toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="h-full w-full flex overflow-hidden">
      <body
        className={`grow-1 w-full p-4 gap-4 flex`}
      >
        <Provider >
        <ToastProvider >
        <SideBar />
        {children}
        </ToastProvider>
        </Provider>
      </body>
    </html>
  );
}
