import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideBar from "./components/sideBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full flex">
      <body
        className={`grow-1 w-full p-4 gap-4 flex`}
      >
        <SideBar />
        {children}
      </body>
    </html>
  );
}
